# Generated by Django 4.2.9 on 2024-01-25 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='categories',
            table='Category',
        ),
    ]
